# GloVe Wiki

In [ ]:
# import gensim.downloader as api
# glove_model = api.load('glove-wiki-gigaword-300')

[==================================================] 100.0% 376.1/376.1MB downloaded


# Download Dataset

In [ ]:
!ls -la /root

total 72
drwx------ 1 root root 4096 Feb  4 17:00 .
drwxr-xr-x 1 root root 4096 Feb  4 16:59 ..
-r-xr-xr-x 1 root root 1169 Jan  1  2000 .bashrc
drwxr-xr-x 1 root root 4096 Feb  1 14:38 .cache
drwx------ 4 root root 4096 Feb  1 14:38 .config
drwxr-xr-x 3 root root 4096 Feb  4 17:01 gensim-data
drwxr-xr-x 5 root root 4096 Feb  1 14:37 .ipython
drwx------ 1 root root 4096 Feb  1 14:37 .jupyter
drwxr-xr-x 2 root root 4096 Feb  4 16:59 .keras
drwx------ 3 root root 4096 Feb  1 14:14 .launchpadlib
drwxr-xr-x 1 root root 4096 Feb  1 14:37 .local
drwxr-xr-x 4 root root 4096 Feb  1 14:37 .npm
-rw-r--r-- 1 root root  161 Jul  9  2019 .profile
-r-xr-xr-x 1 root root  254 Jan  1  2000 .tmux.conf
-rw-r--r-- 1 root root  165 Feb  1 14:37 .wget-hsts


In [ ]:
!kaggle datasets download -d aggarwalrahul/nlp-specialization-data

Traceback (most recent call last):
  File "/usr/local/bin/kaggle", line 5, in <module>
    from kaggle.cli import main
  File "/usr/local/lib/python3.10/dist-packages/kaggle/__init__.py", line 23, in <module>
    api.authenticate()
  File "/usr/local/lib/python3.10/dist-packages/kaggle/api/kaggle_api_extended.py", line 403, in authenticate
    raise IOError('Could not find {}. Make sure it\'s located in'
OSError: Could not find kaggle.json. Make sure it's located in /root/.kaggle. Or use the environment method.


In [ ]:
!ls -la /root

total 76
drwx------ 1 root root 4096 Feb  4 17:04 .
drwxr-xr-x 1 root root 4096 Feb  4 16:59 ..
-r-xr-xr-x 1 root root 1169 Jan  1  2000 .bashrc
drwxr-xr-x 1 root root 4096 Feb  1 14:38 .cache
drwx------ 4 root root 4096 Feb  1 14:38 .config
drwxr-xr-x 3 root root 4096 Feb  4 17:01 gensim-data
drwxr-xr-x 5 root root 4096 Feb  1 14:37 .ipython
drwx------ 1 root root 4096 Feb  1 14:37 .jupyter
drwxr-xr-x 2 root root 4096 Feb  4 17:04 .kaggle
drwxr-xr-x 2 root root 4096 Feb  4 16:59 .keras
drwx------ 3 root root 4096 Feb  1 14:14 .launchpadlib
drwxr-xr-x 1 root root 4096 Feb  1 14:37 .local
drwxr-xr-x 4 root root 4096 Feb  1 14:37 .npm
-rw-r--r-- 1 root root  161 Jul  9  2019 .profile
-r-xr-xr-x 1 root root  254 Jan  1  2000 .tmux.conf
-rw-r--r-- 1 root root  165 Feb  1 14:37 .wget-hsts


So the above step itself creates a `.kaggle` directory within `/root`.

In [ ]:
!ls -la /root/.kaggle

total 12
drwxr-xr-x 2 root root 4096 Feb  4 17:04 .
drwx------ 1 root root 4096 Feb  4 17:04 ..


And we confirn there's no `kaggle.json` in this directory.\
Now, upload `kaggle.json` into `/root/`.


In [ ]:
!ls -la /root

total 80
drwx------ 1 root root 4096 Feb  4 17:04 .
drwxr-xr-x 1 root root 4096 Feb  4 16:59 ..
-r-xr-xr-x 1 root root 1169 Jan  1  2000 .bashrc
drwxr-xr-x 1 root root 4096 Feb  1 14:38 .cache
drwx------ 4 root root 4096 Feb  1 14:38 .config
drwxr-xr-x 3 root root 4096 Feb  4 17:01 gensim-data
drwxr-xr-x 5 root root 4096 Feb  1 14:37 .ipython
drwx------ 1 root root 4096 Feb  1 14:37 .jupyter
drwxr-xr-x 2 root root 4096 Feb  4 17:04 .kaggle
-rw-r--r-- 1 root root   62 Feb  4 17:04 kaggle.json
drwxr-xr-x 2 root root 4096 Feb  4 16:59 .keras
drwx------ 3 root root 4096 Feb  1 14:14 .launchpadlib
drwxr-xr-x 1 root root 4096 Feb  1 14:37 .local
drwxr-xr-x 4 root root 4096 Feb  1 14:37 .npm
-rw-r--r-- 1 root root  161 Jul  9  2019 .profile
-r-xr-xr-x 1 root root  254 Jan  1  2000 .tmux.conf
-rw-r--r-- 1 root root  165 Feb  1 14:37 .wget-hsts


Successfully uploaded, now move this into `/root/.kaggle`.

In [ ]:
!mv /root/kaggle.json /root/.kaggle/

In [ ]:
!ls /root/.kaggle/

kaggle.json


In [ ]:
!kaggle datasets download -d aggarwalrahul/nlp-specialization-data

100% 1.90G/1.90G [01:36<00:00, 21.1MB/s]
100% 1.90G/1.90G [01:36<00:00, 21.2MB/s]


In [ ]:
!unzip -q nlp-specialization-data.zip

In [ ]:
!kaggle datasets download -d ved1104/wiki-sentences

  0% 0.00/92.1k [00:00<?, ?B/s]
100% 92.1k/92.1k [00:00<00:00, 49.1MB/s]


In [ ]:
!unzip -q wiki-sentences.zip

# Explore the dataset
- Novel - Moby-Dick By Herman Melville.txt

In [ ]:
text_file_path = "/content/Novel - Moby-Dick By Herman Melville.txt"

chapter_counter, chapter_contents, chapters = 0, [], []

# read file line by line
with open(text_file_path, "r") as fp:
  for line in fp:
    if line != '\n':
      curr_line = line.replace('  ', ' ')
      curr_line = line.replace('\n', ' ')
      if curr_line.startswith("CHAPTER") or curr_line.startswith("Epilogue"):
        # start of new chapter

        # save contents of old chapter
        if len(chapter_contents) > 0:
          chapters.append(''.join(chapter_contents))
          chapter_contents = []

        print(f"Saved chapter {chapter_counter}.\n")

        # start temp-storing contents of new chapter
        chapter_counter += 1

        print(f"Started temp-storing contents of chapter {chapter_counter}.\n")
      else:
        chapter_contents.append(curr_line)

# Store epilogue
# save contents of old chapter
if len(chapter_contents) > 0:
  chapters.append(''.join(chapter_contents))
  chapter_contents = []

print(len(chapters))

Saved chapter 0.

Started temp-storing contents of chapter 1.

Saved chapter 1.

Started temp-storing contents of chapter 2.

Saved chapter 2.

Started temp-storing contents of chapter 3.

Saved chapter 3.

Started temp-storing contents of chapter 4.

Saved chapter 4.

Started temp-storing contents of chapter 5.

Saved chapter 5.

Started temp-storing contents of chapter 6.

Saved chapter 6.

Started temp-storing contents of chapter 7.

Saved chapter 7.

Started temp-storing contents of chapter 8.

Saved chapter 8.

Started temp-storing contents of chapter 9.

Saved chapter 9.

Started temp-storing contents of chapter 10.

Saved chapter 10.

Started temp-storing contents of chapter 11.

Saved chapter 11.

Started temp-storing contents of chapter 12.

Saved chapter 12.

Started temp-storing contents of chapter 13.

Saved chapter 13.

Started temp-storing contents of chapter 14.

Saved chapter 14.

Started temp-storing contents of chapter 15.

Saved chapter 15.

Started temp-storing cont

In [ ]:
print(chapters[0])

Loomings. Call me Ishmael.  Some years ago--never mind how long precisely--having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world.  It is a way I have of driving off the spleen and regulating the circulation.  Whenever I find myself growing grim about the mouth; whenever it is a damp, drizzly November in my soul; whenever I find myself involuntarily pausing before coffin warehouses, and bringing up the rear of every funeral I meet; and especially whenever my hypos get such an upper hand of me, that it requires a strong moral principle to prevent me from deliberately stepping into the street, and methodically knocking people's hats off--then, I account it high time to get to sea as soon as I can.  This is my substitute for pistol and ball.  With a philosophical flourish Cato throws himself upon his sword; I quietly take to the ship.  There is nothing surprising in this.  If they bu

# Chapter-1 + Chapter-2 training samples

In [ ]:
print(len(chapters[0:2]))

2


In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm")

corpus = ''.join(chapters[:2])
docs = nlp(corpus)
chapter_sents = [sent for sent in docs.sents]

In [ ]:
chapter_sents_wo_stopwords = [' '.join([token.text.lower() for token in sent if not token.is_stop]) for sent in chapter_sents]
chapter_sents_wo_stopwords[:4]

['loomings .',
 'ishmael .  ',
 'years ago -- mind long precisely -- having little money purse , particular interest shore , thought sail little watery world .  ',
 'way driving spleen regulating circulation .  ']

In [ ]:
# fetch sentences from chapter-1
print(f"#sentences = {len(chapter_sents_wo_stopwords)}")

#sentences = 160


In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()

tokenizer.fit_on_texts(chapter_sents_wo_stopwords)

In [ ]:
tokenizer.word_index

{'old': 1,
 'sea': 2,
 'little': 3,
 'way': 4,
 'water': 5,
 'like': 6,
 'whaling': 7,
 'time': 8,
 'voyage': 9,
 'sort': 10,
 'place': 11,
 'night': 12,
 'nantucket': 13,
 'ishmael': 14,
 'thought': 15,
 'land': 16,
 'men': 17,
 'streets': 18,
 'stand': 19,
 'going': 20,
 'great': 21,
 'sailor': 22,
 'new': 23,
 'sign': 24,
 'door': 25,
 'euroclydon': 26,
 'money': 27,
 'particular': 28,
 'world': 29,
 'hand': 30,
 'high': 31,
 'city': 32,
 'come': 33,
 'tell': 34,
 'let': 35,
 'head': 36,
 'poor': 37,
 'passenger': 38,
 'order': 39,
 'things': 40,
 'grand': 41,
 'came': 42,
 'whale': 43,
 'bedford': 44,
 'looked': 45,
 'house': 46,
 'frost': 47,
 'black': 48,
 'lazarus': 49,
 'ago': 50,
 'mind': 51,
 'having': 52,
 'purse': 53,
 'sail': 54,
 'soul': 55,
 'coffin': 56,
 'street': 57,
 'sword': 58,
 'ship': 59,
 'round': 60,
 'right': 61,
 'look': 62,
 'looking': 63,
 'ships': 64,
 'miles': 65,
 'man': 66,
 'set': 67,
 'feet': 68,
 'sleep': 69,
 'winds': 70,
 'image': 71,
 'passengers'

In [ ]:
token_sequences = tokenizer.texts_to_sequences(chapter_sents_wo_stopwords)
print(chapter_sents_wo_stopwords[:1], "\n", token_sequences[:1])

['loomings .'] 
 [[241]]


In [ ]:
input_sequences = []
for tokens in token_sequences:
  for i in range(1, len(tokens)):
    input_sequences.append(tokens[:i+1])
print(input_sequences[:10])

[[92, 50], [92, 50, 51], [92, 50, 51, 93], [92, 50, 51, 93, 242], [92, 50, 51, 93, 242, 52], [92, 50, 51, 93, 242, 52, 3], [92, 50, 51, 93, 242, 52, 3, 27], [92, 50, 51, 93, 242, 52, 3, 27, 53], [92, 50, 51, 93, 242, 52, 3, 27, 53, 28], [92, 50, 51, 93, 242, 52, 3, 27, 53, 28, 243]]


Single-length tokens, i.e. sentences, will be omitted.

In [ ]:
print(f"#Training samples = {len(input_sequences)}")

#Training samples = 1378


In [ ]:
# lets see the sentence with the longest length.
max_seq_length = max([len(seq) for seq in input_sequences])
max_seq_length

43

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_seq_length = 20

padded_input_sequences = pad_sequences(input_sequences, maxlen=max_seq_length, padding='pre')
padded_input_sequences[:3]

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0, 92, 50],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0, 92, 50, 51],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        92, 50, 51, 93]], dtype=int32)

Last column = Target output

In [ ]:
X, y = padded_input_sequences[:, :-1], padded_input_sequences[:, -1]
print(X[:2], "\n", y[:2])

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 92]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 92 50]] 
 [50 51]


In [ ]:
X.shape

(1378, 19)

## Check vocabulary size of spacy vs our corpus

In [ ]:
# tokens
import spacy

# Load the English language model
nlp = spacy.load('en_core_web_sm')
vocabulary = nlp.vocab
all_words = [word.text for word in vocabulary if word.is_alpha]
print(len(all_words))

242


In [ ]:
len(tokenizer.word_index.keys())

692

Hence the vocabulary size of our training text-corpus is larger than spacy's.

## Categorical encoding the target variable

In [ ]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes=1+len(tokenizer.word_index.keys()))
print(y.shape)
print(y[:5])

(1378, 1083)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Dataset-2: Wiki sentences

In [ ]:
import pandas as pd
wiki_raw = pd.read_csv("wiki_sentences_v2.csv")
wiki_raw.head(5)

sentence
0  confused and frustrated, connie decides to lea...
1  later, a woman’s scream is heard in the distance.
2           christian is then paralyzed by an elder.
3                         the temple is set on fire.
4                  outside, the cult wails with him.

In [ ]:
text_corpus = wiki_raw['sentence'].values
text_corpus[:5]

array(['confused and frustrated, connie decides to leave on her own.',
       'later, a woman’s scream is heard in the distance.',
       'christian is then paralyzed by an elder.',
       'the temple is set on fire.', 'outside, the cult wails with him.'],
      dtype=object)

In [ ]:
import spacy
import re

nlp = spacy.load('en_core_web_sm')
docs = nlp('. '.join(text_corpus))

corpus_sents = [sent for sent in docs.sents]
tokenized_corpus_sents = [[re.sub(r'[^a-zA-Z0-9\s]', '', token.text.lower()) for token in sent if token.text.isalnum()] for sent in corpus_sents]
print(tokenized_corpus_sents[:15])

[['confused', 'and', 'frustrated', 'connie', 'decides', 'to', 'leave', 'on', 'her', 'own'], ['later', 'a', 'woman', 'scream', 'is', 'heard', 'in', 'the', 'distance'], ['christian', 'is', 'then', 'paralyzed', 'by', 'an', 'elder', 'the', 'temple', 'is', 'set', 'on', 'fire'], ['outside', 'the', 'cult', 'wails', 'with', 'him'], ['it', 'a', 'parable', 'of', 'a', 'woman', 'religious', 'mackenzie', 'and', 'craig', 'vincent', 'joined', 'the', 'cast', 'later', 'craig', 'di', 'francia', 'and', 'action', 'bronson', 'were', 'revealed', 'to', 'have', 'joined', 'the', 'cast', 'sebastian', 'maniscalco', 'and', 'paul', 'ben', 'victor', 'were', 'later', 'revealed', 'as', 'being', 'part', 'of', 'the', 'cast', 'we', 'just', 'tried', 'to', 'make', 'the', 'film'], ['we', 'went', 'through', 'all', 'these', 'tests', 'and', 'things'], ['m', 'global', 'was', 'also', 'circling', 'to', 'bid', 'for', 'the', 'film', 'international', 'sales', 'rights'], ['canadian', 'musician', 'robbie', 'robertson', 'supervised', 

In [ ]:
# check words per sentence not in glove
for i, sent in enumerate(tokenized_corpus_sents):
  for j, token in enumerate(sent):
    if token not in glove_model:
      print(i, j, sent, token)

27 10 ['on', 'december', '10', '2018', 'the', 'film', 'first', 'teaser', 'poster', 'and', 'ccxp', 'trailer', 'were', 'released', 'in', 'april', '2019', 'the', 'main', 'theatrical', 'poster', 'was', 'released', 'online'] ccxp
30 4 ['the', '4k', 'release', 'includes', 'hdr10', 'hdr10'] hdr10
30 5 ['the', '4k', 'release', 'includes', 'hdr10', 'hdr10'] hdr10
47 1 ['la', 'femis', 'in', 'paris', 'tel', 'aviv', 'university', 'and', 'vancouver', 'film', 'school'] femis
60 43 ['film', 'is', 'a', '1965', 'short', 'film', 'written', 'by', 'samuel', 'beckett', 'his', 'only', 'screenplay', 'a', 'second', 'draft', 'was', 'produced', 'by', '22', 'may', 'and', 'a', '40', 'leaf', 'shooting', 'script', 'followed', 'thereafter', 'both', 'beckett', 'and', 'the', 'director', 'alan', 'schneider', 'were', 'interested', 'in', 'zero', 'mostel', 'and', 'jack', 'macgowran'] macgowran
70 10 ['he', 'half', 'starts', 'from', 'the', 'chair', 'then', 'stiffens', 'esse', 'est', 'percipi', 'aut', 'percipere'] percipi
7

In [ ]:
'''
27 10
30 4
30 5
47 1
60 43
70 10
70 12
76 9
79 24'''

['on', 'december', '10', '2018', 'the', 'film', 'first', 'teaser', 'poster', 'and', 'ccxp', 'trailer', 'were', 'released', 'in', 'april', '2019', 'the', 'main', 'theatrical', 'poster', 'was', 'released', 'online']


In [ ]:
text_corpus[:50]

array(['confused and frustrated, connie decides to leave on her own.',
       'later, a woman’s scream is heard in the distance.',
       'christian is then paralyzed by an elder.',
       'the temple is set on fire.', 'outside, the cult wails with him.',
       "it's a parable of a woman's religious awakening—",
       'c. mackenzie, and craig vincent joined the cast.',
       'later, craig di francia and action bronson were revealed to have joined the cast.',
       'sebastian maniscalco and paul ben-victor were later revealed as being part of the cast.',
       'we just tried to make the film.',
       'we went through all these tests and things  ',
       "m global was also circling to bid for the film's international sales rights.",
       'canadian musician robbie robertson supervised the soundtrack.',
       'it features both original and existing music tracks.',
       'it is the worst reviewed film in the franchise.',
       'but she injures quicksilver and accidentally kills 

# Model Definition

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM, Masking

model = Sequential()
model.add(Masking(mask_value=0, input_shape=(X.shape[-1],)))
model.add(Embedding(input_dim=y.shape[-1], output_dim=100)) # vocab size, embedding vector size, x_train each sequence size.
model.add(LSTM(150)) # dimensionality of h_t and c_t.
model.add(Dense(y.shape[-1], activation='softmax'))

print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 masking (Masking)           (None, 19)                0         
                                                                 
 embedding (Embedding)       (None, 19, 100)           108300    
                                                                 
 lstm (LSTM)                 (None, 150)               150600    
                                                                 
 dense (Dense)               (None, 1083)              163533    
                                                                 
Total params: 422433 (1.61 MB)
Trainable params: 422433 (1.61 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


If LSTM(150) is used, with embedding vector size = 100, then the reason for #parameters = 150600 is as follows:
1. There are 4 layers wherein $x_t$(of dimensionality 100) is converted to $c_t$(of dimensionality 150) - 4 matrices of dimensionality 100 x 150 $\Rightarrow$ 100 x 600 = 60,000.
2. Those 4 layers also convert $h_{t-1}$ to $c_t$ or $h_t$ - 4 matrices of dimensionality 150 x 150 $\Rightarrow$ 150 x 600 = 90,000.
3. Those 4 layers will each have 150 bias terms - 600 bias params.

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
history = model.fit(X_train, y_train, epochs=20, validation_split=0.2)

Epoch 1/20
28/28 [==============================] - 7s 145ms/step - loss: 6.9891 - accuracy: 0.0068 - val_loss: 6.9981 - val_accuracy: 0.0000e+00
Epoch 2/20
28/28 [==============================] - 3s 108ms/step - loss: 6.8400 - accuracy: 0.0148 - val_loss: 7.5638 - val_accuracy: 0.0045
Epoch 3/20
28/28 [==============================] - 3s 96ms/step - loss: 6.6064 - accuracy: 0.0068 - val_loss: 7.9691 - val_accuracy: 0.0000e+00
Epoch 4/20
28/28 [==============================] - 2s 69ms/step - loss: 6.4971 - accuracy: 0.0136 - val_loss: 8.3721 - val_accuracy: 0.0045
Epoch 5/20
28/28 [==============================] - 2s 86ms/step - loss: 6.4279 - accuracy: 0.0068 - val_loss: 8.7517 - val_accuracy: 0.0045
Epoch 6/20
28/28 [==============================] - 1s 41ms/step - loss: 6.3126 - accuracy: 0.0125 - val_loss: 8.9361 - val_accuracy: 0.0000e+00
Epoch 7/20
28/28 [==============================] - 1s 30ms/step - loss: 6.1331 - accuracy: 0.0136 - val_loss: 9.3542 - val_accuracy: 0.0000

In [ ]:
tokenizer.sequences_to_texts(X_test[:10])

['having night day night following new bedford ere embark destined port',
 "passengers sea sick grow quarrelsome don't sleep nights enjoy general thing no passenger",
 'stood sharp bleak corner tempestuous wind euroclydon kept worse howling poor paul',
 'careless look meant uses public entering',
 'wild distant seas rolled island bulk undeliverable nameless',
 'nantucket adventurous little sloop forth partly',
 'voyage passenger feel mystical vibration told ship',
 'bright red',
 'world head winds far prevalent winds astern violate pythagorean maxim commodore quarter deck gets atmosphere',
 'halting steps paced streets passed sign crossed harpoons but looked expensive']

In [ ]:
X_test[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,  52,  12, 208,  12, 199,
        23,  44, 814, 201, 815, 816], dtype=int32)

In [ ]:
import numpy as np

idx = np.where(y_test[0]==1)
print(idx, "\n", tokenizer.sequences_to_texts(idx))

(array([205]),) 
 ['matter']


In [ ]:
import numpy as np

orig_texts = tokenizer.sequences_to_texts(X_test[0:1])
actual_tokens = np.where(y_test[0:1]==1)[-1]
actuals = tokenizer.sequences_to_texts(np.expand_dims(actual_tokens, axis=1))

for i, orig_text in enumerate(orig_texts):
  # tokenize
  tokens = tokenizer.texts_to_sequences([orig_text])[0]

  # padded
  padded_tokens = pad_sequences([tokens], maxlen=max_seq_length-1, padding='pre')

  pred_word_idx = np.argmax(model.predict(padded_tokens))
  for word, index in tokenizer.word_index.items():
    if index == pred_word_idx:
      print(f"\nPrediction: {orig_text} {word}\nActual: {orig_text} {actuals[i]}\n\n")

1/1 [==============================] - 0s 21ms/step

Prediction: having night day night following new bedford ere embark destined port officer
Actual: having night day night following new bedford ere embark destined port matter




In [ ]:
# checking probability value of actual word
pred_proba = model.predict(padded_tokens)[0]

print(np.argmax(pred_proba))

sorted_idx_arr = np.argsort(-pred_proba)
print(sorted_idx_arr, "\n")
print(np.where(sorted_idx_arr == 205))

1/1 [==============================] - 0s 18ms/step
161
[ 161  684  817 ... 1021  889  476] 

(array([1054]),)


In [ ]:
embedding_mat = model.layers[1].weights[0].numpy()
print(embedding_mat.shape)

(1083, 100)


In [ ]:
print(np.linalg.norm(embedding_mat[205] - embedding_mat[161]))

1.2156974


## Debugging

In [ ]:
tokenizer.sequences_to_texts(X_test[3:4])

['touches sense honour particularly come']

In [ ]:
orig_text = tokenizer.sequences_to_texts(X_test[3:4])[0]

# tokenize
tokens = tokenizer.texts_to_sequences([orig_text])[0]

# padded
padded_tokens = pad_sequences([tokens], maxlen=42, padding='pre')
print(padded_tokens, "\n")

embedding_weights = model.layers[1].weights[0].numpy()
print(embedding_weights.shape, padded_tokens.shape)

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0 465 466 467 468  28]] 

(693, 100) (1, 42)


In [ ]:
tokens

[107, 502, 503, 108, 504, 100, 505, 8, 106]

In [ ]:
# vector embedding learnt for token 49, i.e. the word "find"
sample_vector = embedding_weights[tokens]
sample_vector

array([[-8.87491833e-03, -8.12704489e-02, -9.24819782e-02,
        -3.43927145e-02, -1.12872154e-01, -1.74582731e-02,
         6.24025203e-02,  1.03610149e-02, -1.72306057e-02,
        -5.97352535e-02, -9.69668776e-02, -3.52124088e-02,
         2.95872334e-02, -1.43064058e-03,  4.68431301e-02,
         5.58189936e-02, -2.78820265e-02, -1.22435093e-02,
         1.89718399e-02,  1.14153493e-02, -1.14680827e-03,
        -5.44914454e-02,  3.94688509e-02,  4.64047231e-02,
        -4.82053496e-02, -1.42954821e-02,  9.74695832e-02,
        -7.57231377e-03,  6.14762679e-02,  9.02036205e-03,
        -2.34461818e-02,  3.45824659e-03, -2.62204558e-02,
        -5.55235483e-02, -2.75786817e-02, -5.34683280e-02,
         3.89359985e-03, -2.52451980e-03, -3.47846411e-02,
        -6.93523288e-02, -6.57875240e-02, -2.79152114e-02,
        -2.11869553e-02, -5.78194633e-02, -2.32880861e-02,
        -4.09110710e-02, -3.95749770e-02, -2.92731319e-02,
         1.88605103e-03, -1.51346764e-03,  9.78060365e-0

In [ ]:
# LSTM weights
model.layers[2].weights

[<tf.Variable 'lstm_1/lstm_cell/kernel:0' shape=(100, 600) dtype=float32, numpy=
 array([[ 0.00451121,  0.09245729,  0.04163727, ...,  0.02155741,
          0.02202455, -0.07014849],
        [ 0.01827898,  0.03008018, -0.01206193, ...,  0.02649412,
          0.03295738, -0.0043415 ],
        [-0.04093692, -0.02926932,  0.01488503, ...,  0.16543731,
          0.00711225,  0.08484776],
        ...,
        [ 0.07064778, -0.02740278,  0.03244099, ...,  0.00617169,
         -0.06786746,  0.0158754 ],
        [ 0.044472  , -0.01867642, -0.00558644, ...,  0.03649435,
         -0.04394033,  0.02645582],
        [-0.04302791, -0.01138854, -0.07018625, ..., -0.10180692,
          0.08164143, -0.02635729]], dtype=float32)>,
 <tf.Variable 'lstm_1/lstm_cell/recurrent_kernel:0' shape=(150, 600) dtype=float32, numpy=
 array([[ 0.02558224, -0.10382847, -0.04005468, ...,  0.02037578,
          0.06402472, -0.00481263],
        [ 0.0111407 , -0.03120139, -0.05677051, ..., -0.0251716 ,
         -0.01306

# Stacked RNNs

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, SimpleRNN

stacked_rnn_model = Sequential()
stacked_rnn_model.add(Masking(mask_value=0, input_shape=(X.shape[-1],)))
stacked_rnn_model.add(Embedding(input_dim=y.shape[-1], output_dim=100)) # vocab size, embedding vector size, x_train each sequence size.
stacked_rnn_model.add(SimpleRNN(150, return_sequences=True))
stacked_rnn_model.add(SimpleRNN(100))
stacked_rnn_model.add(Dense(y.shape[-1], activation='softmax'))

print(stacked_rnn_model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 masking_1 (Masking)         (None, 9)                 0         
                                                                 
 embedding_1 (Embedding)     (None, 9, 100)            108300    
                                                                 
 simple_rnn (SimpleRNN)      (None, 9, 150)            37650     
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 100)               25100     
                                                                 
 dense_1 (Dense)             (None, 1083)              109383    
                                                                 
Total params: 280433 (1.07 MB)
Trainable params: 280433 (1.07 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [ ]:
stacked_rnn_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
stacked_rnn_history = stacked_rnn_model.fit(X_train, y_train, epochs=20, validation_split=0.2)

Epoch 1/20
28/28 [==============================] - 7s 138ms/step - loss: 6.9960 - accuracy: 0.0034 - val_loss: 6.9944 - val_accuracy: 0.0000e+00
Epoch 2/20
28/28 [==============================] - 2s 68ms/step - loss: 6.7005 - accuracy: 0.0772 - val_loss: 7.3845 - val_accuracy: 0.0045
Epoch 3/20
28/28 [==============================] - 2s 64ms/step - loss: 6.2795 - accuracy: 0.1862 - val_loss: 7.7107 - val_accuracy: 0.0045
Epoch 4/20
28/28 [==============================] - 2s 56ms/step - loss: 5.8645 - accuracy: 0.2894 - val_loss: 7.9305 - val_accuracy: 0.0045
Epoch 5/20
28/28 [==============================] - 1s 45ms/step - loss: 5.4640 - accuracy: 0.4052 - val_loss: 7.8273 - val_accuracy: 0.0136
Epoch 6/20
28/28 [==============================] - 2s 74ms/step - loss: 5.0741 - accuracy: 0.4733 - val_loss: 7.9779 - val_accuracy: 0.0000e+00
Epoch 7/20
28/28 [==============================] - 1s 50ms/step - loss: 4.6906 - accuracy: 0.5153 - val_loss: 7.9282 - val_accuracy: 0.0136
Epoc

In [ ]:
for i, orig_text in enumerate(orig_texts):
  # tokenize
  tokens = tokenizer.texts_to_sequences([orig_text])[0]

  # padded
  padded_tokens = pad_sequences([tokens], maxlen=9, padding='pre')

  pred_word_idx = np.argmax(stacked_rnn_model.predict(padded_tokens))
  for word, index in tokenizer.word_index.items():
    if index == pred_word_idx:
      print(f"\nPrediction: {orig_text} {word}\nActual: {orig_text} {actuals[i]}\n\n")

1/1 [==============================] - 0s 223ms/step

Prediction: careless look nantucket
Actual: careless look meant


1/1 [==============================] - 0s 20ms/step

Prediction: careless look meant uses
Actual: careless look meant uses


1/1 [==============================] - 0s 27ms/step

Prediction: careless look meant uses public
Actual: careless look meant uses public


1/1 [==============================] - 0s 23ms/step

Prediction: careless look meant uses public boisterous
Actual: careless look meant uses public entering


1/1 [==============================] - 0s 21ms/step

Prediction: careless look meant uses public entering thing
Actual: careless look meant uses public entering thing


1/1 [==============================] - 0s 19ms/step

Prediction: careless look meant uses public entering thing stumble
Actual: careless look meant uses public entering thing stumble


1/1 [==============================] - 0s 19ms/step

Prediction: careless look meant uses public enteri

# Stacked LSTMs

## Double Stacking

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM

stacked_lstm_model = Sequential()
stacked_lstm_model.add(Masking(mask_value=0, input_shape=(X.shape[-1],)))
stacked_lstm_model.add(Embedding(input_dim=y.shape[-1], output_dim=150)) # vocab size, embedding vector size, x_train each sequence size.
stacked_lstm_model.add(LSTM(150, return_sequences=True))
stacked_lstm_model.add(LSTM(100))
stacked_lstm_model.add(Dense(y.shape[-1], activation='softmax'))

print(stacked_lstm_model.summary())

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 masking_2 (Masking)         (None, 9)                 0         
                                                                 
 embedding_2 (Embedding)     (None, 9, 150)            162450    
                                                                 
 lstm_1 (LSTM)               (None, 9, 150)            180600    
                                                                 
 lstm_2 (LSTM)               (None, 100)               100400    
                                                                 
 dense_2 (Dense)             (None, 1083)              109383    
                                                                 
Total params: 552833 (2.11 MB)
Trainable params: 552833 (2.11 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [ ]:
stacked_lstm_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
stacked_lstm_history = stacked_lstm_model.fit(X_train, y_train, epochs=20, validation_split=0.2)

Epoch 1/20
28/28 [==============================] - 9s 165ms/step - loss: 6.9898 - accuracy: 0.0011 - val_loss: 6.9929 - val_accuracy: 0.0045
Epoch 2/20
28/28 [==============================] - 2s 79ms/step - loss: 6.8814 - accuracy: 0.0057 - val_loss: 7.5819 - val_accuracy: 0.0045
Epoch 3/20
28/28 [==============================] - 2s 77ms/step - loss: 6.6567 - accuracy: 0.0079 - val_loss: 7.6137 - val_accuracy: 0.0000e+00
Epoch 4/20
28/28 [==============================] - 2s 70ms/step - loss: 6.4747 - accuracy: 0.0034 - val_loss: 8.3572 - val_accuracy: 0.0000e+00
Epoch 5/20
28/28 [==============================] - 1s 49ms/step - loss: 6.2654 - accuracy: 0.0079 - val_loss: 8.6991 - val_accuracy: 0.0000e+00
Epoch 6/20
28/28 [==============================] - 1s 27ms/step - loss: 6.0758 - accuracy: 0.0057 - val_loss: 9.3287 - val_accuracy: 0.0045
Epoch 7/20
28/28 [==============================] - 1s 39ms/step - loss: 5.9448 - accuracy: 0.0079 - val_loss: 9.2891 - val_accuracy: 0.0045


In [ ]:
for i, orig_text in enumerate(orig_texts):
  # tokenize
  tokens = tokenizer.texts_to_sequences([orig_text])[0]

  # padded
  padded_tokens = pad_sequences([tokens], maxlen=9, padding='pre')

  pred_word_idx = np.argmax(stacked_lstm_model.predict(padded_tokens))
  for word, index in tokenizer.word_index.items():
    if index == pred_word_idx:
      print(f"\nPrediction: {orig_text} {word}\nActual: {orig_text} {actuals[i]}\n\n")

1/1 [==============================] - 1s 674ms/step

Prediction: careless look sea
Actual: careless look meant


1/1 [==============================] - 0s 23ms/step

Prediction: careless look meant sea
Actual: careless look meant uses


1/1 [==============================] - 0s 23ms/step

Prediction: careless look meant uses nantucket
Actual: careless look meant uses public


1/1 [==============================] - 0s 20ms/step

Prediction: careless look meant uses public nantucket
Actual: careless look meant uses public entering


1/1 [==============================] - 0s 18ms/step

Prediction: careless look meant uses public entering great
Actual: careless look meant uses public entering thing


1/1 [==============================] - 0s 21ms/step

Prediction: careless look meant uses public entering thing way
Actual: careless look meant uses public entering thing stumble


1/1 [==============================] - 0s 20ms/step

Prediction: careless look meant uses public entering thing 

## 3-stacked LSTMs

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM

stacked_lstm_model_3 = Sequential()
stacked_lstm_model_3.add(Masking(mask_value=0, input_shape=(X.shape[-1],)))
stacked_lstm_model_3.add(Embedding(input_dim=y.shape[-1], output_dim=150)) # vocab size, embedding vector size, x_train each sequence size.
stacked_lstm_model_3.add(LSTM(150, return_sequences=True))
stacked_lstm_model_3.add(LSTM(100, return_sequences=True))
stacked_lstm_model_3.add(LSTM(100))
stacked_lstm_model_3.add(Dense(y.shape[-1], activation='softmax'))

print(stacked_lstm_model_3.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 masking_3 (Masking)         (None, 9)                 0         
                                                                 
 embedding_3 (Embedding)     (None, 9, 150)            162450    
                                                                 
 lstm_3 (LSTM)               (None, 9, 150)            180600    
                                                                 
 lstm_4 (LSTM)               (None, 9, 100)            100400    
                                                                 
 lstm_5 (LSTM)               (None, 100)               80400     
                                                                 
 dense_3 (Dense)             (None, 1083)              109383    
                                                                 
Total params: 633233 (2.42 MB)
Trainable params: 63323

In [ ]:
stacked_lstm_model_3.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
stacked_lstm_model_3_history = stacked_lstm_model_3.fit(X_train, y_train, epochs=20, validation_split=0.2)

Epoch 1/20
28/28 [==============================] - 10s 186ms/step - loss: 6.9896 - accuracy: 0.0023 - val_loss: 6.9906 - val_accuracy: 0.0045
Epoch 2/20
28/28 [==============================] - 2s 78ms/step - loss: 6.9129 - accuracy: 0.0034 - val_loss: 7.4100 - val_accuracy: 0.0000e+00
Epoch 3/20
28/28 [==============================] - 1s 49ms/step - loss: 6.6826 - accuracy: 0.0057 - val_loss: 7.5601 - val_accuracy: 0.0000e+00
Epoch 4/20
28/28 [==============================] - 1s 32ms/step - loss: 6.4576 - accuracy: 0.0102 - val_loss: 8.3036 - val_accuracy: 0.0045
Epoch 5/20
28/28 [==============================] - 1s 23ms/step - loss: 6.2543 - accuracy: 0.0114 - val_loss: 8.7138 - val_accuracy: 0.0045
Epoch 6/20
28/28 [==============================] - 1s 19ms/step - loss: 6.1012 - accuracy: 0.0114 - val_loss: 8.8869 - val_accuracy: 0.0045
Epoch 7/20
28/28 [==============================] - 1s 18ms/step - loss: 5.9878 - accuracy: 0.0068 - val_loss: 9.4436 - val_accuracy: 0.0000e+00

In [ ]:
for i, orig_text in enumerate(orig_texts):
  # tokenize
  tokens = tokenizer.texts_to_sequences([orig_text])[0]

  # padded
  padded_tokens = pad_sequences([tokens], maxlen=9, padding='pre')

  pred_word_idx = np.argmax(stacked_lstm_model_3.predict(padded_tokens))
  for word, index in tokenizer.word_index.items():
    if index == pred_word_idx:
      print(f"\nPrediction: {orig_text} {word}\nActual: {orig_text} {actuals[i]}\n\n")

1/1 [==============================] - 1s 1s/step

Prediction: careless look sea
Actual: careless look meant


1/1 [==============================] - 0s 34ms/step

Prediction: careless look meant sea
Actual: careless look meant uses


1/1 [==============================] - 0s 29ms/step

Prediction: careless look meant uses old
Actual: careless look meant uses public


1/1 [==============================] - 0s 27ms/step

Prediction: careless look meant uses public old
Actual: careless look meant uses public entering


1/1 [==============================] - 0s 29ms/step

Prediction: careless look meant uses public entering like
Actual: careless look meant uses public entering thing


1/1 [==============================] - 0s 34ms/step

Prediction: careless look meant uses public entering thing strong
Actual: careless look meant uses public entering thing stumble


1/1 [==============================] - 0s 33ms/step

Prediction: careless look meant uses public entering thing stumble stree

In [ ]:
i = 0
orig_text = orig_texts[i]

# tokenize
tokens = tokenizer.texts_to_sequences([orig_text])[0]

# padded
padded_tokens = pad_sequences([tokens], maxlen=9, padding='pre')

pred_proba = stacked_lstm_model_3.predict(padded_tokens)
pred_word_idx = np.argmax(pred_proba)
for word, index in tokenizer.word_index.items():
  if index == pred_word_idx:
    print(f"\nPrediction: {orig_text} {word}\nActual: {orig_text} {actuals[i]}\n\n")

1/1 [==============================] - 0s 20ms/step

Prediction: careless look sea
Actual: careless look meant




In [ ]:
pred_proba.shape

NameError: name 'pred_proba' is not defined